# Generated by Django 4.2.17 on 2024-12-13 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookclub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="bookclub",
        ),
    ]
