# Generated by Django 4.2.17 on 2024-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookclub", "0006_book_chosen_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="location",
            field=models.CharField(max_length=500),
        ),
    ]
