# Generated by Django 4.2.17 on 2024-12-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookclub", "0007_alter_meeting_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
