# Generated by Django 4.2.17 on 2024-12-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookclub", "0010_remove_book_cover_book_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
