# Generated by Django 4.2.17 on 2024-12-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookclub", "0011_remove_book_cover_image_book_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
